on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
              server: ftp-tonom.alwaysdata.net  # Mets ton vrai hôte ici
              username: ton_user_alwaysdata     # Mets ton vrai user ici
              password: ton_password            # Mets ton vrai pass ici
              protocol: ftps
              timeout: 60000
